name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:

    - uses: actions/checkout@v1
    
    - name: Restore NuGets
      run: nuget restore SQLite.sln
      
    - name: Install reportgenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Build and Test
      run: |
        set -e
        cd tests/SQLite.Tests
        dotnet test /p:AltCover=true /p:AltCoverForce=true
        reportgenerator -reports:coverage.xml -targetdir:./CoverageReport
      
    - name: Package
      run: |
        make nuget

    - uses: actions/upload-artifact@master
      with:
        name: Packages
        path: PackagesOut

