name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:

    - uses: actions/checkout@v1
    
    - name: Restore NuGets
      run: nuget restore SQLite.sln

    - name: Build and Test
      run: cd tests/SQLite.Tests && dotnet test /p:AltCover=true
      
    - name: Package
      run: |
        make nuget

    - uses: actions/upload-artifact@master
      with:
        name: Packages
        path: PackagesOut

